-- Make menu_items easier to edit in Supabase table editor.
-- 1) Add primary key so rows can be edited/deleted in UI.
-- 2) Store meal/tags as plain text (comma-separated) instead of text[] arrays.

alter table public.menu_items
  add column if not exists id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.menu_items'::regclass
      and conname = 'menu_items_pkey'
  ) then
    alter table public.menu_items
      add constraint menu_items_pkey primary key (id);
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_items'
      and column_name = 'meal'
      and data_type = 'ARRAY'
  ) then
    alter table public.menu_items
      add column if not exists meal_text text;

    update public.menu_items
    set meal_text = coalesce(meal_text, array_to_string(meal, ', '), '');

    alter table public.menu_items
      drop column meal;

    alter table public.menu_items
      rename column meal_text to meal;
  end if;
end
$$;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'menu_items'
      and column_name = 'tags'
      and data_type = 'ARRAY'
  ) then
    alter table public.menu_items
      add column if not exists tags_text text;

    update public.menu_items
    set tags_text = coalesce(tags_text, array_to_string(tags, ', '), '');

    alter table public.menu_items
      drop column tags;

    alter table public.menu_items
      rename column tags_text to tags;
  end if;
end
$$;

alter table public.menu_items
  alter column meal set default '',
  alter column meal set not null,
  alter column tags set default '',
  alter column tags set not null;

alter table public.menu_items
  drop constraint if exists menu_items_meal_check,
  drop constraint if exists menu_items_tags_check;
